version: "3"
services:
  gateway:
    build: gateway
    depends_on:
      - frontend
    expose:
      - 80
    ports:
      - ${HTTP_PORT:-80}:80
  backend:
    build: backend
    expose:
      - 8080
    volumes:
      - ./data:/data
  frontend:
    build: frontend
    image: syrtis-jezero-frontend
    environment:
      API_BASE_URL: /tiles
      NODE_ENV: production
