# NOTE: This docker-compose file only covers backend processes
# right now. The frontend is built locally and generally will live
# on a different machine than the data services.
services:
  gateway:
    build: gateway
    expose:
      - 80
    ports:
      - ${HTTP_PORT:-80}:80
    depends_on:
      - vector_tiles
      - backend
  backend:
    image: protomaps/go-pmtiles:v1.27.2
    command: ["serve", "$TILESET_BUCKET_PREFIX", "--bucket", "$TILESET_BUCKET"]
    environment:
      - TILESET_BUCKET
      - TILESET_BUCKET_PREFIX
  vector_tiles:
    image: pramsey/pg_tileserv:20250131
    environment:
      - DATABASE_URL
    expose:
      - 7800
  api:
    build: api
    environment:
      - DATABASE_URL
      - API_PORT=7801
    expose:
      - 7801
