version: "3"
services:
  gateway:
    build: gateway
    depends_on:
      - frontend
    expose:
      - 80
    ports:
      - ${HTTP_PORT:-80}:80
  backend:
    build: backend
    expose:
      - 8080
    volumes:
      - ./data:/data
  frontend:
    build:
      context: frontend
      args:
        - PUBLIC_URL=${PUBLIC_URL:-"/"}
        - NODE_ENV=production
    image: syrtis-jezero-frontend
