# NOTE: This docker-compose file only covers backend processes
# right now. The frontend is built locally and generally will live
# on a different machine than the data services.
version: "3"
services:
  gateway:
    build: gateway
    expose:
      - 80
    ports:
      - ${HTTP_PORT:-80}:80
  backend:
    build: backend
    expose:
      - 8080
    volumes:
      - ./data:/data
  tileserver:
    image: pramsey/pg_tileserv
    environment:
      - DATABASE_URL=postgres://postgres@database/mars_syrtis
    depends_on:
      - database
    ports:
      - 7800:7800
    expose:
      - 7800
  database:
    image: postgis/postgis:13-3.0
    volumes:
      - db_cluster:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mars_syrtis
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 54321:5432
    expose:
      - 54321
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"] 
volumes:
  db_cluster: