# NOTE: This docker-compose file only covers backend processes
# right now. The frontend is built locally and generally will live
# on a different machine than the data services.
services:
  gateway:
    build: gateway
    volumes:
      - ./gateway/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - TILESET_BASE_URL
  cache:
    image: varnish:7.7.0-alpine
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - ./gateway/cache.vcl:/etc/varnish/default.vcl
    # special mount to serve cache from memory
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    environment:
      - VARNISH_SIZE=100M
  vector_tiles:
    image: pramsey/pg_tileserv:20250131
    environment:
      - DATABASE_URL
    expose:
      - 7800
  postgrest:
    image: postgrest/postgrest:v12.2.11
    environment:
      - PGRST_DB_URI=$DATABASE_URL
      - PGRST_DB_SCHEMAS=map_units_api
      - PGRST_DB_ANON_ROLE=web_anon
      - PGRST_LOG_LEVEL=info
    expose:
      - 3000
