
user  nginx;
worker_processes  3;

error_log  stderr warn;
pid        /var/run/nginx.pid;


events {
  worker_connections  4096;
}


http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

  access_log  stdout main;

  sendfile        on;
  #tcp_nopush     on;

  keepalive_timeout  65;

  #gzip  on;

  server {
    location / {
      root /usr/share/nginx/html/;
      try_files $uri $uri/ /index.html;
    }

    # Cache tiles
    location /tiles/ {
      # https://stackoverflow.com/questions/44639182/nginx-proxy-amazon-s3-resources
      proxy_pass http://raster_tiles:8080/;
    }

    location /vector-tiles/ {
      # https://stackoverflow.com/questions/44639182/nginx-proxy-amazon-s3-resources

      limit_except GET {
        deny all;
      }
      proxy_pass http://vector_tiles:7800/;
      proxy_hide_header Access-Control-Allow-Origin;

    }

    location /api/v1/ {
      limit_except GET {
        deny all;
      }
      proxy_pass http://api:7801/;
    }
  }
}
