#!/usr/bin/env python
# Taken from davenquinn/paper-components
import re
import sys

cite_re = re.compile(r"@[\w-]+")
ignores = set(["@fig", "@sec", "@eq", "@tbl"])
for line in sys.stdin:
    citekeys = re.findall(cite_re, line)
    for key in citekeys:
        if key not in ignores:
            print(key[1:])
            keys.add(key)
