#!/bin/bash -e

export BUNDLE_DIR="$(pwd)/mars/syrtis-jezero"
export API_BASE_URL=https://birdnest.geology.wisc.edu/mars-data
export PUBLIC_URL=/mars/syrtis-jezero

mkdir -p $BUNDLE_DIR

npm --prefix frontend run build:web

#rclone sync $BUNDLE_DIR macrostrat-s3:macrostrat-sites$PUBLIC_URL

