#!/bin/bash
# Description: Export database to a binary `pg_dump` archive
# Borrowed from Sparrow

[ -z $1 ] && echo "Please specify a file" >&2

internal_name=/tmp/database-dump.pg-dump
container_id=$(docker-compose ps -q database 2>/dev/null)

if [ -z $container_id ]; then
  echo "Database container must be running"
  exit 1
fi

docker exec $container_id \
  pg_dump -Fc -C -Upostgres -f $internal_name mars_syrtis

docker cp "$container_id:$internal_name" "$1"

docker exec $container_id rm -f $internal_name